tree_benchmark_config:
  trees: # which trees to run the benchmark on
    - RBTree
    - AVLTree
    - SplayTree
    - TreapTree
  parameters:
    benchmark_mode: "all"  # available modes: "all", "random", "sorted"
    memcheck_mode: false  # whether to execute the benchmarks with the valgrind massif tool (for memory consumption analysis)
  execution:
    run_benchmarks: true  # set to `false` to omit benchmarks execution
