tree_benchmark_config:
  trees: # which trees to run the benchmark on
    - RBTree
    - AVLTree
    - SplayTree
    - TreapTree
  parameters:
    benchmark_mode: "all"  # available modes: "all", "random", "sorted"
  execution:
    run_benchmarks: true # set to `false` to omit benchmarks execution
